name: Release fosslight_scanner_gui

on:
  release:
    types: [published]

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    name: Build and Release ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install Snapcraft (Ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo snap install snapcraft --classic
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Extract version number
        id: extract_version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')" >> $GITHUB_ENV

      - name: Build Electron app
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn build
        
      - name: Build artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            yarn electron-builder --linux deb appimage --config.extraMetadata.version=${{ env.VERSION }}
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            yarn electron-builder --mac dmg zip --config.extraMetadata.version=${{ env.VERSION }}
          else
            yarn electron-builder --win nsis zip --config.extraMetadata.version=${{ env.VERSION }}
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-artifacts
          path: |
            dist/*${{ env.VERSION }}*.exe
            dist/*${{ env.VERSION }}*.dmg
            dist/*${{ env.VERSION }}*.deb
            dist/*${{ env.VERSION }}*.AppImage
            dist/*${{ env.VERSION }}*.zip
          if-no-files-found: ignore

      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*${{ env.VERSION }}*.exe
            dist/*${{ env.VERSION }}*.dmg
            dist/*${{ env.VERSION }}*.deb
            dist/*${{ env.VERSION }}*.AppImage
            dist/*${{ env.VERSION }}*.zip
        if: startsWith(github.ref, 'refs/tags/')
